server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.mybatis: DEBUG
    com.github.narh.sample.mybatis: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    
mybatis:
  type-aliases-package: com.github.narh.sample.mybatis.domain.model
  type-handlers-package: com.github.narh.sample.mybatis.domain.type
  mapper-locations: classpath*:/META-INF/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30